// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="spmv_spmv,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.274000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2003,HLS_SYN_LUT=3107,HLS_VERSION=2022_1}" *)

module spmv (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 8;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [2:0] rowPtr_address0;
reg    rowPtr_ce0;
wire   [31:0] rowPtr_q0;
wire   [31:0] columnIndex_q0;
wire   [31:0] values_q0;
wire   [1:0] y_address0;
reg    y_ce0;
reg    y_we0;
wire   [31:0] y_d0;
wire   [31:0] x_q0;
wire   [63:0] zext_ln16_fu_199_p1;
reg   [63:0] zext_ln16_reg_423;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln16_fu_187_p2;
wire   [1:0] trunc_ln18_fu_204_p1;
reg   [1:0] trunc_ln18_reg_428;
reg   [31:0] k_reg_438;
wire    ap_CS_fsm_state3;
reg   [31:0] rowPtr_load_reg_448;
wire    ap_CS_fsm_state4;
wire   [2:0] grp_spmv_Pipeline_L2_fu_158_ap_return;
reg   [2:0] targetBlock_reg_453;
wire    ap_CS_fsm_state5;
wire    grp_spmv_Pipeline_L2_fu_158_ap_start;
wire    grp_spmv_Pipeline_L2_fu_158_ap_done;
wire    grp_spmv_Pipeline_L2_fu_158_ap_idle;
wire    grp_spmv_Pipeline_L2_fu_158_ap_ready;
wire   [3:0] grp_spmv_Pipeline_L2_fu_158_values_address0;
wire    grp_spmv_Pipeline_L2_fu_158_values_ce0;
wire   [3:0] grp_spmv_Pipeline_L2_fu_158_columnIndex_address0;
wire    grp_spmv_Pipeline_L2_fu_158_columnIndex_ce0;
wire   [1:0] grp_spmv_Pipeline_L2_fu_158_x_address0;
wire    grp_spmv_Pipeline_L2_fu_158_x_ce0;
wire   [31:0] grp_spmv_Pipeline_L2_fu_158_y0_0_out;
wire    grp_spmv_Pipeline_L2_fu_158_y0_0_out_ap_vld;
wire   [31:0] grp_spmv_Pipeline_L2_fu_158_y0_1_6_out;
wire    grp_spmv_Pipeline_L2_fu_158_y0_1_6_out_ap_vld;
wire   [31:0] grp_spmv_Pipeline_L2_fu_158_y0_1_5_out;
wire    grp_spmv_Pipeline_L2_fu_158_y0_1_5_out_ap_vld;
wire   [31:0] grp_spmv_Pipeline_L2_fu_158_y0_1_4_out;
wire    grp_spmv_Pipeline_L2_fu_158_y0_1_4_out_ap_vld;
wire   [31:0] grp_spmv_Pipeline_L2_fu_158_y0_1_3_out;
wire    grp_spmv_Pipeline_L2_fu_158_y0_1_3_out_ap_vld;
wire   [31:0] grp_spmv_Pipeline_L2_fu_158_y0_1_2_out;
wire    grp_spmv_Pipeline_L2_fu_158_y0_1_2_out_ap_vld;
wire   [31:0] grp_spmv_Pipeline_L2_fu_158_y0_1_1_out;
wire    grp_spmv_Pipeline_L2_fu_158_y0_1_1_out_ap_vld;
wire   [31:0] grp_spmv_Pipeline_L2_fu_158_y0_1_out;
wire    grp_spmv_Pipeline_L2_fu_158_y0_1_out_ap_vld;
reg    grp_spmv_Pipeline_L2_fu_158_ap_start_reg;
reg   [31:0] y0_0_loc_fu_120;
reg   [31:0] y0_1_6_loc_fu_116;
reg   [31:0] y0_1_5_loc_fu_112;
reg   [31:0] y0_1_4_loc_fu_108;
reg   [31:0] y0_1_3_loc_fu_104;
reg   [31:0] y0_1_2_loc_fu_100;
reg   [31:0] y0_1_1_loc_fu_96;
reg   [31:0] y0_1_loc_fu_92;
wire   [63:0] p_cast_fu_240_p1;
wire    ap_CS_fsm_state6;
reg   [2:0] i_fu_88;
wire   [2:0] indvars_iv_next6_fu_193_p2;
wire   [3:0] shl_ln_fu_213_p3;
wire   [4:0] zext_ln18_fu_220_p1;
wire   [4:0] empty_16_fu_224_p2;
wire   [2:0] tmp_1_fu_230_p4;
wire   [0:0] empty_17_fu_269_p2;
wire   [0:0] empty_19_fu_282_p2;
wire   [31:0] empty_18_fu_274_p3;
wire   [0:0] empty_21_fu_295_p2;
wire   [31:0] empty_20_fu_287_p3;
wire   [0:0] empty_23_fu_308_p2;
wire   [31:0] empty_22_fu_300_p3;
wire   [0:0] empty_25_fu_321_p2;
wire   [31:0] empty_24_fu_313_p3;
wire   [0:0] empty_27_fu_334_p2;
wire   [31:0] empty_26_fu_326_p3;
wire   [0:0] empty_29_fu_347_p2;
wire   [31:0] empty_28_fu_339_p3;
wire   [31:0] y0_lcssa_fu_352_p3;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_spmv_Pipeline_L2_fu_158_ap_start_reg = 1'b0;
end

spmv_spmv_Pipeline_L2 grp_spmv_Pipeline_L2_fu_158(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_spmv_Pipeline_L2_fu_158_ap_start),
    .ap_done(grp_spmv_Pipeline_L2_fu_158_ap_done),
    .ap_idle(grp_spmv_Pipeline_L2_fu_158_ap_idle),
    .ap_ready(grp_spmv_Pipeline_L2_fu_158_ap_ready),
    .sext_ln18(k_reg_438),
    .sext_ln18_1(rowPtr_load_reg_448),
    .values_address0(grp_spmv_Pipeline_L2_fu_158_values_address0),
    .values_ce0(grp_spmv_Pipeline_L2_fu_158_values_ce0),
    .values_q0(values_q0),
    .columnIndex_address0(grp_spmv_Pipeline_L2_fu_158_columnIndex_address0),
    .columnIndex_ce0(grp_spmv_Pipeline_L2_fu_158_columnIndex_ce0),
    .columnIndex_q0(columnIndex_q0),
    .x_address0(grp_spmv_Pipeline_L2_fu_158_x_address0),
    .x_ce0(grp_spmv_Pipeline_L2_fu_158_x_ce0),
    .x_q0(x_q0),
    .y0_0_out(grp_spmv_Pipeline_L2_fu_158_y0_0_out),
    .y0_0_out_ap_vld(grp_spmv_Pipeline_L2_fu_158_y0_0_out_ap_vld),
    .y0_1_6_out(grp_spmv_Pipeline_L2_fu_158_y0_1_6_out),
    .y0_1_6_out_ap_vld(grp_spmv_Pipeline_L2_fu_158_y0_1_6_out_ap_vld),
    .y0_1_5_out(grp_spmv_Pipeline_L2_fu_158_y0_1_5_out),
    .y0_1_5_out_ap_vld(grp_spmv_Pipeline_L2_fu_158_y0_1_5_out_ap_vld),
    .y0_1_4_out(grp_spmv_Pipeline_L2_fu_158_y0_1_4_out),
    .y0_1_4_out_ap_vld(grp_spmv_Pipeline_L2_fu_158_y0_1_4_out_ap_vld),
    .y0_1_3_out(grp_spmv_Pipeline_L2_fu_158_y0_1_3_out),
    .y0_1_3_out_ap_vld(grp_spmv_Pipeline_L2_fu_158_y0_1_3_out_ap_vld),
    .y0_1_2_out(grp_spmv_Pipeline_L2_fu_158_y0_1_2_out),
    .y0_1_2_out_ap_vld(grp_spmv_Pipeline_L2_fu_158_y0_1_2_out_ap_vld),
    .y0_1_1_out(grp_spmv_Pipeline_L2_fu_158_y0_1_1_out),
    .y0_1_1_out_ap_vld(grp_spmv_Pipeline_L2_fu_158_y0_1_1_out_ap_vld),
    .y0_1_out(grp_spmv_Pipeline_L2_fu_158_y0_1_out),
    .y0_1_out_ap_vld(grp_spmv_Pipeline_L2_fu_158_y0_1_out_ap_vld),
    .ap_return(grp_spmv_Pipeline_L2_fu_158_ap_return)
);

spmv_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .y_address0(y_address0),
    .y_ce0(y_ce0),
    .y_we0(y_we0),
    .y_d0(y_d0),
    .rowPtr_address0(rowPtr_address0),
    .rowPtr_ce0(rowPtr_ce0),
    .rowPtr_q0(rowPtr_q0),
    .columnIndex_address0(grp_spmv_Pipeline_L2_fu_158_columnIndex_address0),
    .columnIndex_ce0(grp_spmv_Pipeline_L2_fu_158_columnIndex_ce0),
    .columnIndex_q0(columnIndex_q0),
    .values_address0(grp_spmv_Pipeline_L2_fu_158_values_address0),
    .values_ce0(grp_spmv_Pipeline_L2_fu_158_values_ce0),
    .values_q0(values_q0),
    .x_address0(grp_spmv_Pipeline_L2_fu_158_x_address0),
    .x_ce0(grp_spmv_Pipeline_L2_fu_158_x_ce0),
    .x_q0(x_q0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_spmv_Pipeline_L2_fu_158_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_spmv_Pipeline_L2_fu_158_ap_start_reg <= 1'b1;
        end else if ((grp_spmv_Pipeline_L2_fu_158_ap_ready == 1'b1)) begin
            grp_spmv_Pipeline_L2_fu_158_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_88 <= 3'd0;
    end else if (((icmp_ln16_fu_187_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_88 <= indvars_iv_next6_fu_193_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        k_reg_438 <= rowPtr_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rowPtr_load_reg_448 <= rowPtr_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        targetBlock_reg_453 <= grp_spmv_Pipeline_L2_fu_158_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln16_fu_187_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln18_reg_428 <= trunc_ln18_fu_204_p1;
        zext_ln16_reg_423[2 : 0] <= zext_ln16_fu_199_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_spmv_Pipeline_L2_fu_158_y0_0_out_ap_vld == 1'b1))) begin
        y0_0_loc_fu_120 <= grp_spmv_Pipeline_L2_fu_158_y0_0_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_spmv_Pipeline_L2_fu_158_y0_1_1_out_ap_vld == 1'b1))) begin
        y0_1_1_loc_fu_96 <= grp_spmv_Pipeline_L2_fu_158_y0_1_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_spmv_Pipeline_L2_fu_158_y0_1_2_out_ap_vld == 1'b1))) begin
        y0_1_2_loc_fu_100 <= grp_spmv_Pipeline_L2_fu_158_y0_1_2_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_spmv_Pipeline_L2_fu_158_y0_1_3_out_ap_vld == 1'b1))) begin
        y0_1_3_loc_fu_104 <= grp_spmv_Pipeline_L2_fu_158_y0_1_3_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_spmv_Pipeline_L2_fu_158_y0_1_4_out_ap_vld == 1'b1))) begin
        y0_1_4_loc_fu_108 <= grp_spmv_Pipeline_L2_fu_158_y0_1_4_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_spmv_Pipeline_L2_fu_158_y0_1_5_out_ap_vld == 1'b1))) begin
        y0_1_5_loc_fu_112 <= grp_spmv_Pipeline_L2_fu_158_y0_1_5_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_spmv_Pipeline_L2_fu_158_y0_1_6_out_ap_vld == 1'b1))) begin
        y0_1_6_loc_fu_116 <= grp_spmv_Pipeline_L2_fu_158_y0_1_6_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_spmv_Pipeline_L2_fu_158_y0_1_out_ap_vld == 1'b1))) begin
        y0_1_loc_fu_92 <= grp_spmv_Pipeline_L2_fu_158_y0_1_out;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_spmv_Pipeline_L2_fu_158_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln16_fu_187_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln16_fu_187_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        rowPtr_address0 = p_cast_fu_240_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rowPtr_address0 = zext_ln16_fu_199_p1;
    end else begin
        rowPtr_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        rowPtr_ce0 = 1'b1;
    end else begin
        rowPtr_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        y_ce0 = 1'b1;
    end else begin
        y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        y_we0 = 1'b1;
    end else begin
        y_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln16_fu_187_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_spmv_Pipeline_L2_fu_158_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_16_fu_224_p2 = (zext_ln18_fu_220_p1 + 5'd4);

assign empty_17_fu_269_p2 = ((targetBlock_reg_453 == 3'd0) ? 1'b1 : 1'b0);

assign empty_18_fu_274_p3 = ((empty_17_fu_269_p2[0:0] == 1'b1) ? y0_0_loc_fu_120 : y0_1_loc_fu_92);

assign empty_19_fu_282_p2 = ((targetBlock_reg_453 == 3'd1) ? 1'b1 : 1'b0);

assign empty_20_fu_287_p3 = ((empty_19_fu_282_p2[0:0] == 1'b1) ? y0_1_6_loc_fu_116 : empty_18_fu_274_p3);

assign empty_21_fu_295_p2 = ((targetBlock_reg_453 == 3'd2) ? 1'b1 : 1'b0);

assign empty_22_fu_300_p3 = ((empty_21_fu_295_p2[0:0] == 1'b1) ? y0_1_5_loc_fu_112 : empty_20_fu_287_p3);

assign empty_23_fu_308_p2 = ((targetBlock_reg_453 == 3'd3) ? 1'b1 : 1'b0);

assign empty_24_fu_313_p3 = ((empty_23_fu_308_p2[0:0] == 1'b1) ? y0_1_4_loc_fu_108 : empty_22_fu_300_p3);

assign empty_25_fu_321_p2 = ((targetBlock_reg_453 == 3'd4) ? 1'b1 : 1'b0);

assign empty_26_fu_326_p3 = ((empty_25_fu_321_p2[0:0] == 1'b1) ? y0_1_3_loc_fu_104 : empty_24_fu_313_p3);

assign empty_27_fu_334_p2 = ((targetBlock_reg_453 == 3'd5) ? 1'b1 : 1'b0);

assign empty_28_fu_339_p3 = ((empty_27_fu_334_p2[0:0] == 1'b1) ? y0_1_2_loc_fu_100 : empty_26_fu_326_p3);

assign empty_29_fu_347_p2 = ((targetBlock_reg_453 == 3'd6) ? 1'b1 : 1'b0);

assign grp_spmv_Pipeline_L2_fu_158_ap_start = grp_spmv_Pipeline_L2_fu_158_ap_start_reg;

assign icmp_ln16_fu_187_p2 = ((i_fu_88 == 3'd4) ? 1'b1 : 1'b0);

assign indvars_iv_next6_fu_193_p2 = (i_fu_88 + 3'd1);

assign p_cast_fu_240_p1 = tmp_1_fu_230_p4;

assign shl_ln_fu_213_p3 = {{trunc_ln18_reg_428}, {2'd0}};

assign tmp_1_fu_230_p4 = {{empty_16_fu_224_p2[4:2]}};

assign trunc_ln18_fu_204_p1 = i_fu_88[1:0];

assign y0_lcssa_fu_352_p3 = ((empty_29_fu_347_p2[0:0] == 1'b1) ? y0_1_1_loc_fu_96 : empty_28_fu_339_p3);

assign y_address0 = zext_ln16_reg_423;

assign y_d0 = y0_lcssa_fu_352_p3;

assign zext_ln16_fu_199_p1 = i_fu_88;

assign zext_ln18_fu_220_p1 = shl_ln_fu_213_p3;

always @ (posedge ap_clk) begin
    zext_ln16_reg_423[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
end

endmodule //spmv
