// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module spmv_accel_spvm_kernel (
        values_address0,
        values_ce0,
        values_d0,
        values_q0,
        values_we0,
        values_address1,
        values_ce1,
        values_d1,
        values_q1,
        values_we1,
        cols_address0,
        cols_ce0,
        cols_d0,
        cols_q0,
        cols_we0,
        cols_address1,
        cols_ce1,
        cols_d1,
        cols_q1,
        cols_we1,
        rows_address0,
        rows_ce0,
        rows_d0,
        rows_q0,
        rows_we0,
        rows_address1,
        rows_ce1,
        rows_d1,
        rows_q1,
        rows_we1,
        x_local_address0,
        x_local_ce0,
        x_local_d0,
        x_local_q0,
        x_local_we0,
        x_local_address1,
        x_local_ce1,
        x_local_d1,
        x_local_q1,
        x_local_we1,
        y_address0,
        y_ce0,
        y_d0,
        y_q0,
        y_we0,
        y_address1,
        y_ce1,
        y_d1,
        y_q1,
        y_we1,
        row_size,
        data_size,
        ap_clk,
        ap_rst,
        row_size_ap_vld,
        ap_start,
        data_size_ap_vld,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


output  [3:0] values_address0;
output   values_ce0;
output  [31:0] values_d0;
input  [31:0] values_q0;
output   values_we0;
output  [3:0] values_address1;
output   values_ce1;
output  [31:0] values_d1;
input  [31:0] values_q1;
output   values_we1;
output  [3:0] cols_address0;
output   cols_ce0;
output  [31:0] cols_d0;
input  [31:0] cols_q0;
output   cols_we0;
output  [3:0] cols_address1;
output   cols_ce1;
output  [31:0] cols_d1;
input  [31:0] cols_q1;
output   cols_we1;
output  [1:0] rows_address0;
output   rows_ce0;
output  [31:0] rows_d0;
input  [31:0] rows_q0;
output   rows_we0;
output  [1:0] rows_address1;
output   rows_ce1;
output  [31:0] rows_d1;
input  [31:0] rows_q1;
output   rows_we1;
output  [1:0] x_local_address0;
output   x_local_ce0;
output  [31:0] x_local_d0;
input  [31:0] x_local_q0;
output   x_local_we0;
output  [1:0] x_local_address1;
output   x_local_ce1;
output  [31:0] x_local_d1;
input  [31:0] x_local_q1;
output   x_local_we1;
output  [1:0] y_address0;
output   y_ce0;
output  [31:0] y_d0;
input  [31:0] y_q0;
output   y_we0;
output  [1:0] y_address1;
output   y_ce1;
output  [31:0] y_d1;
input  [31:0] y_q1;
output   y_we1;
input  [31:0] row_size;
input  [31:0] data_size;
input   ap_clk;
input   ap_rst;
input   row_size_ap_vld;
input   ap_start;
input   data_size_ap_vld;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_start;
wire    spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_done;
wire    spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_continue;
wire    spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_idle;
wire    spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_ready;
wire    spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_start_out;
wire    spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_start_write;
wire   [1:0] spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_rows_address0;
wire    spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_rows_ce0;
wire   [31:0] spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_rows_fifo_din;
wire    spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_rows_fifo_write;
wire   [31:0] spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_row_size_c_din;
wire    spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_row_size_c_write;
wire    spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_start;
wire    spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_done;
wire    spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_continue;
wire    spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_idle;
wire    spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_ready;
wire   [31:0] spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_values_fifo_din;
wire    spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_values_fifo_write;
wire   [31:0] spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_cols_fifo_din;
wire    spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_cols_fifo_write;
wire   [3:0] spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_values_address0;
wire    spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_values_ce0;
wire   [3:0] spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_cols_address0;
wire    spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_cols_ce0;
wire    spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_start;
wire    spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_done;
wire    spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_continue;
wire    spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_idle;
wire    spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_ready;
wire    spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_values_fifo_read;
wire    spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_cols_fifo_read;
wire   [1:0] spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_x_local_address0;
wire    spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_x_local_ce0;
wire    spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_rows_fifo_read;
wire   [31:0] spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_results_fifo_din;
wire    spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_results_fifo_write;
wire    spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_ap_start;
wire    spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_ap_done;
wire    spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_ap_continue;
wire    spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_ap_idle;
wire    spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_ap_ready;
wire    spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_row_size_read;
wire    spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_results_fifo_read;
wire   [1:0] spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_y_address0;
wire    spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_y_ce0;
wire    spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_y_we0;
wire   [31:0] spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_y_d0;
wire    rows_fifo_full_n;
wire   [31:0] rows_fifo_dout;
wire   [1:0] rows_fifo_num_data_valid;
wire   [1:0] rows_fifo_fifo_cap;
wire    rows_fifo_empty_n;
wire    row_size_c_full_n;
wire   [31:0] row_size_c_dout;
wire   [2:0] row_size_c_num_data_valid;
wire   [2:0] row_size_c_fifo_cap;
wire    row_size_c_empty_n;
wire    values_fifo_full_n;
wire   [31:0] values_fifo_dout;
wire   [1:0] values_fifo_num_data_valid;
wire   [1:0] values_fifo_fifo_cap;
wire    values_fifo_empty_n;
wire    cols_fifo_full_n;
wire   [31:0] cols_fifo_dout;
wire   [1:0] cols_fifo_num_data_valid;
wire   [1:0] cols_fifo_fifo_cap;
wire    cols_fifo_empty_n;
wire    results_fifo_full_n;
wire   [31:0] results_fifo_dout;
wire   [1:0] results_fifo_num_data_valid;
wire   [1:0] results_fifo_fifo_cap;
wire    results_fifo_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_ready;
wire    ap_sync_spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_ready;
reg    ap_sync_reg_spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_ready;
wire    ap_sync_spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_ready;
reg    ap_sync_reg_spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_ready;
wire    ap_sync_spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_ready;
wire   [0:0] start_for_spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_din;
wire    start_for_spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_full_n;
wire   [0:0] start_for_spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_dout;
wire    start_for_spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_ready = 1'b0;
#0 ap_sync_reg_spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_ready = 1'b0;
#0 ap_sync_reg_spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_ready = 1'b0;
end

spmv_accel_spvm_kernel_Loop_VITIS_LOOP_30_1_proc2 spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_start),
    .start_full_n(start_for_spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_full_n),
    .ap_done(spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_done),
    .ap_continue(spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_continue),
    .ap_idle(spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_idle),
    .ap_ready(spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_ready),
    .start_out(spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_start_out),
    .start_write(spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_start_write),
    .row_size(row_size),
    .rows_address0(spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_rows_address0),
    .rows_ce0(spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_rows_ce0),
    .rows_q0(rows_q0),
    .rows_fifo_din(spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_rows_fifo_din),
    .rows_fifo_num_data_valid(rows_fifo_num_data_valid),
    .rows_fifo_fifo_cap(rows_fifo_fifo_cap),
    .rows_fifo_full_n(rows_fifo_full_n),
    .rows_fifo_write(spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_rows_fifo_write),
    .row_size_c_din(spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_row_size_c_din),
    .row_size_c_num_data_valid(row_size_c_num_data_valid),
    .row_size_c_fifo_cap(row_size_c_fifo_cap),
    .row_size_c_full_n(row_size_c_full_n),
    .row_size_c_write(spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_row_size_c_write)
);

spmv_accel_spvm_kernel_Loop_VITIS_LOOP_35_2_proc3 spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_start),
    .ap_done(spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_done),
    .ap_continue(spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_continue),
    .ap_idle(spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_idle),
    .ap_ready(spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_ready),
    .values_fifo_din(spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_values_fifo_din),
    .values_fifo_num_data_valid(values_fifo_num_data_valid),
    .values_fifo_fifo_cap(values_fifo_fifo_cap),
    .values_fifo_full_n(values_fifo_full_n),
    .values_fifo_write(spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_values_fifo_write),
    .cols_fifo_din(spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_cols_fifo_din),
    .cols_fifo_num_data_valid(cols_fifo_num_data_valid),
    .cols_fifo_fifo_cap(cols_fifo_fifo_cap),
    .cols_fifo_full_n(cols_fifo_full_n),
    .cols_fifo_write(spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_cols_fifo_write),
    .data_size(data_size),
    .values_address0(spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_values_address0),
    .values_ce0(spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_values_ce0),
    .values_q0(values_q0),
    .cols_address0(spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_cols_address0),
    .cols_ce0(spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_cols_ce0),
    .cols_q0(cols_q0)
);

spmv_accel_spvm_kernel_Loop_VITIS_LOOP_52_3_proc4 spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_start),
    .ap_done(spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_done),
    .ap_continue(spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_continue),
    .ap_idle(spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_idle),
    .ap_ready(spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_ready),
    .data_size(data_size),
    .values_fifo_dout(values_fifo_dout),
    .values_fifo_num_data_valid(values_fifo_num_data_valid),
    .values_fifo_fifo_cap(values_fifo_fifo_cap),
    .values_fifo_empty_n(values_fifo_empty_n),
    .values_fifo_read(spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_values_fifo_read),
    .cols_fifo_dout(cols_fifo_dout),
    .cols_fifo_num_data_valid(cols_fifo_num_data_valid),
    .cols_fifo_fifo_cap(cols_fifo_fifo_cap),
    .cols_fifo_empty_n(cols_fifo_empty_n),
    .cols_fifo_read(spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_cols_fifo_read),
    .x_local_address0(spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_x_local_address0),
    .x_local_ce0(spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_x_local_ce0),
    .x_local_q0(x_local_q0),
    .rows_fifo_dout(rows_fifo_dout),
    .rows_fifo_num_data_valid(rows_fifo_num_data_valid),
    .rows_fifo_fifo_cap(rows_fifo_fifo_cap),
    .rows_fifo_empty_n(rows_fifo_empty_n),
    .rows_fifo_read(spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_rows_fifo_read),
    .results_fifo_din(spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_results_fifo_din),
    .results_fifo_num_data_valid(results_fifo_num_data_valid),
    .results_fifo_fifo_cap(results_fifo_fifo_cap),
    .results_fifo_full_n(results_fifo_full_n),
    .results_fifo_write(spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_results_fifo_write)
);

spmv_accel_spvm_kernel_Loop_VITIS_LOOP_70_4_proc5 spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_ap_start),
    .ap_done(spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_ap_done),
    .ap_continue(spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_ap_continue),
    .ap_idle(spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_ap_idle),
    .ap_ready(spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_ap_ready),
    .row_size_dout(row_size_c_dout),
    .row_size_num_data_valid(row_size_c_num_data_valid),
    .row_size_fifo_cap(row_size_c_fifo_cap),
    .row_size_empty_n(row_size_c_empty_n),
    .row_size_read(spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_row_size_read),
    .results_fifo_dout(results_fifo_dout),
    .results_fifo_num_data_valid(results_fifo_num_data_valid),
    .results_fifo_fifo_cap(results_fifo_fifo_cap),
    .results_fifo_empty_n(results_fifo_empty_n),
    .results_fifo_read(spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_results_fifo_read),
    .y_address0(spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_y_address0),
    .y_ce0(spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_y_ce0),
    .y_we0(spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_y_we0),
    .y_d0(spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_y_d0)
);

spmv_accel_fifo_w32_d2_S rows_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_rows_fifo_din),
    .if_full_n(rows_fifo_full_n),
    .if_write(spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_rows_fifo_write),
    .if_dout(rows_fifo_dout),
    .if_num_data_valid(rows_fifo_num_data_valid),
    .if_fifo_cap(rows_fifo_fifo_cap),
    .if_empty_n(rows_fifo_empty_n),
    .if_read(spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_rows_fifo_read)
);

spmv_accel_fifo_w32_d3_S row_size_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_row_size_c_din),
    .if_full_n(row_size_c_full_n),
    .if_write(spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_row_size_c_write),
    .if_dout(row_size_c_dout),
    .if_num_data_valid(row_size_c_num_data_valid),
    .if_fifo_cap(row_size_c_fifo_cap),
    .if_empty_n(row_size_c_empty_n),
    .if_read(spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_row_size_read)
);

spmv_accel_fifo_w32_d2_S values_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_values_fifo_din),
    .if_full_n(values_fifo_full_n),
    .if_write(spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_values_fifo_write),
    .if_dout(values_fifo_dout),
    .if_num_data_valid(values_fifo_num_data_valid),
    .if_fifo_cap(values_fifo_fifo_cap),
    .if_empty_n(values_fifo_empty_n),
    .if_read(spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_values_fifo_read)
);

spmv_accel_fifo_w32_d2_S cols_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_cols_fifo_din),
    .if_full_n(cols_fifo_full_n),
    .if_write(spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_cols_fifo_write),
    .if_dout(cols_fifo_dout),
    .if_num_data_valid(cols_fifo_num_data_valid),
    .if_fifo_cap(cols_fifo_fifo_cap),
    .if_empty_n(cols_fifo_empty_n),
    .if_read(spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_cols_fifo_read)
);

spmv_accel_fifo_w32_d2_S results_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_results_fifo_din),
    .if_full_n(results_fifo_full_n),
    .if_write(spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_results_fifo_write),
    .if_dout(results_fifo_dout),
    .if_num_data_valid(results_fifo_num_data_valid),
    .if_fifo_cap(results_fifo_fifo_cap),
    .if_empty_n(results_fifo_empty_n),
    .if_read(spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_results_fifo_read)
);

spmv_accel_start_for_spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0 start_for_spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_din),
    .if_full_n(start_for_spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_full_n),
    .if_write(spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_start_write),
    .if_dout(start_for_spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_dout),
    .if_empty_n(start_for_spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_empty_n),
    .if_read(spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_ready <= ap_sync_spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_ready <= ap_sync_spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_ready <= ap_sync_spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_ready;
        end
    end
end

assign ap_done = spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_ap_done;

assign ap_idle = (spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_ap_idle & spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_idle & spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_idle & spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_ready = (ap_sync_spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_ready & ap_sync_spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_ready & ap_sync_spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_ready);

assign ap_sync_spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_ready = (spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_ready | ap_sync_reg_spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_ready);

assign ap_sync_spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_ready = (spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_ready | ap_sync_reg_spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_ready);

assign ap_sync_spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_ready = (spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_ready | ap_sync_reg_spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_ready);

assign cols_address0 = spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_cols_address0;

assign cols_address1 = 4'd0;

assign cols_ce0 = spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_cols_ce0;

assign cols_ce1 = 1'b0;

assign cols_d0 = 32'd0;

assign cols_d1 = 32'd0;

assign cols_we0 = 1'b0;

assign cols_we1 = 1'b0;

assign rows_address0 = spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_rows_address0;

assign rows_address1 = 2'd0;

assign rows_ce0 = spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_rows_ce0;

assign rows_ce1 = 1'b0;

assign rows_d0 = 32'd0;

assign rows_d1 = 32'd0;

assign rows_we0 = 1'b0;

assign rows_we1 = 1'b0;

assign spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_continue = 1'b1;

assign spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_start = ((ap_sync_reg_spvm_kernel_Loop_VITIS_LOOP_30_1_proc2_U0_ap_ready ^ 1'b1) & ap_start);

assign spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_continue = 1'b1;

assign spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_start = ((ap_sync_reg_spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_ap_ready ^ 1'b1) & ap_start);

assign spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_continue = 1'b1;

assign spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_start = ((ap_sync_reg_spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_ap_ready ^ 1'b1) & ap_start);

assign spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_ap_continue = ap_continue;

assign spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_ap_start = start_for_spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_empty_n;

assign start_for_spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_din = 1'b1;

assign values_address0 = spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_values_address0;

assign values_address1 = 4'd0;

assign values_ce0 = spvm_kernel_Loop_VITIS_LOOP_35_2_proc3_U0_values_ce0;

assign values_ce1 = 1'b0;

assign values_d0 = 32'd0;

assign values_d1 = 32'd0;

assign values_we0 = 1'b0;

assign values_we1 = 1'b0;

assign x_local_address0 = spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_x_local_address0;

assign x_local_address1 = 2'd0;

assign x_local_ce0 = spvm_kernel_Loop_VITIS_LOOP_52_3_proc4_U0_x_local_ce0;

assign x_local_ce1 = 1'b0;

assign x_local_d0 = 32'd0;

assign x_local_d1 = 32'd0;

assign x_local_we0 = 1'b0;

assign x_local_we1 = 1'b0;

assign y_address0 = spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_y_address0;

assign y_address1 = 2'd0;

assign y_ce0 = spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_y_ce0;

assign y_ce1 = 1'b0;

assign y_d0 = spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_y_d0;

assign y_d1 = 32'd0;

assign y_we0 = spvm_kernel_Loop_VITIS_LOOP_70_4_proc5_U0_y_we0;

assign y_we1 = 1'b0;

endmodule //spmv_accel_spvm_kernel
